# Generated by Django 3.2.5 on 2021-09-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20210925_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_user_img',
            field=models.FileField(blank=True, upload_to='', verbose_name='commentUserImg'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
