# Generated by Django 3.2.5 on 2021-09-26 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210926_1348'),
        ('article', '0008_alter_comment_comment_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_user_img',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile', verbose_name='commentUserImg'),
        ),
    ]
