# Generated by Django 3.2.5 on 2021-09-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_alter_comment_comment_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_user_img',
            field=models.FileField(blank=True, upload_to='', verbose_name='commentUserImg'),
        ),
    ]
