# Generated by Django 3.2.5 on 2021-09-26 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_account_img'),
        ('article', '0012_alter_comment_comment_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_user_img',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile', verbose_name='commentUserImg'),
        ),
    ]
