# Generated by Django 3.2.5 on 2021-09-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_img',
            field=models.FileField(default='user-01.png', upload_to='', verbose_name='accountImg'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userAbout',
            field=models.CharField(blank=True, max_length=200, verbose_name='userAbout'),
        ),
    ]
