# Generated by Django 3.2.5 on 2021-09-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profile_account_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_img',
            field=models.FileField(default='user-01.png', upload_to='', verbose_name='accountImg'),
        ),
    ]
